const express = require('express');
const router = express.Router();
const ContactPage = require('../models/ContactPage');
const ContactInquiry = require('../models/ContactInquiry');
const nodemailer = require('nodemailer');

// Configure nodemailer transporter
const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true, // Use SSL
    auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS ? process.env.MAIL_PASS.replace(/\s/g, '') : '' // Strip spaces from App Password
    },
    tls: {
        rejectUnauthorized: false
    }
});

// GET /api/contact/page — Fetch contact page content
router.get('/page', async (req, res) => {
    try {
        let contactDetails = await ContactPage.findOne();
        if (!contactDetails) {
            contactDetails = await ContactPage.create({});
        }
        res.json(contactDetails);
    } catch (err) {
        console.error('Error fetching contact page:', err);
        res.status(500).json({ message: 'Server error', error: err.message });
    }
});

// PUT /api/contact/page — Update contact page content (Super Admin)
router.put('/page', async (req, res) => {
    try {
        let contactDetails = await ContactPage.findOne();
        if (!contactDetails) {
            contactDetails = await ContactPage.create(req.body);
        } else {
            Object.assign(contactDetails, req.body);
            await contactDetails.save();
        }
        res.json({ message: 'Contact page updated successfully', data: contactDetails });
    } catch (err) {
        console.error('Error updating contact page:', err);
        res.status(500).json({ message: 'Server error', error: err.message });
    }
});

// POST /api/contact/inquire — Submit a contact form inquiry
router.post('/inquire', async (req, res) => {
    try {
        const { firstName, lastName, name, email, phone, message } = req.body;
        
        // Combine names if firstName/lastName provided
        const finalName = name || `${firstName || ''} ${lastName || ''}`.trim();

        if (!finalName || !email || !message) {
            return res.status(400).json({ message: 'Name, email, and message are required.' });
        }
        
        // 1. Save to Database
        const newInquiry = new ContactInquiry({ name: finalName, email, phone, message });
        await newInquiry.save();

        // 2. Send Email
        const mailOptions = {
            from: `"MZ School Website" <${process.env.MAIL_USER}>`,
            to: 'mountzion2021@gmail.com', // Recipients
            subject: `New Contact Inquiry: ${finalName}`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
                    <div style="background: #0B3C5D; color: #ffffff; padding: 20px; text-align: center;">
                        <h2 style="margin: 0;">New Contact Inquiry</h2>
                    </div>
                    <div style="padding: 20px; background: #ffffff;">
                        <p style="color: #64748b; font-size: 0.9rem; margin-top: 0;">You have received a new message from the school website contact form.</p>
                        
                        <div style="margin-bottom: 20px; border-left: 4px solid #0B3C5D; padding-left: 15px;">
                            <p style="margin: 5px 0;"><strong>Name:</strong> ${finalName}</p>
                            <p style="margin: 5px 0;"><strong>Email:</strong> ${email}</p>
                            <p style="margin: 5px 0;"><strong>Phone:</strong> ${phone || 'Not provided'}</p>
                        </div>

                        <div style="background: #f8fafc; padding: 15px; border-radius: 6px;">
                            <p style="margin: 0 0 10px 0; font-weight: bold; color: #1e293b;">Message:</p>
                            <p style="margin: 0; color: #334155; line-height: 1.6;">${message}</p>
                        </div>
                    </div>
                    <div style="background: #f1f5f9; padding: 15px; text-align: center; font-size: 0.8rem; color: #64748b;">
                        This email was automatically generated by Mount Zion School Management System.
                    </div>
                </div>
            `
        };

        // Attempt to send email but don't block response if it fails (optional)
        try {
            await transporter.sendMail(mailOptions);
            console.log('Inquiry email sent successfully.');
        } catch (mailErr) {
            console.error('Error sending email:', mailErr);
            // We still return 201 because the database save was successful
        }
        
        res.status(201).json({ message: 'Your message has been sent successfully. We will get back to you soon!', data: newInquiry });
    } catch (err) {
        console.error('Error submitting inquiry:', err);
        res.status(500).json({ message: 'Server error', error: err.message });
    }
});

// GET /api/contact/inquiries — Fetch all inquiries (Super Admin)
router.get('/inquiries', async (req, res) => {
    try {
        const inquiries = await ContactInquiry.find().sort({ createdAt: -1 });
        res.json(inquiries);
    } catch (err) {
        console.error('Error fetching inquiries:', err);
        res.status(500).json({ message: 'Server error', error: err.message });
    }
});

module.exports = router;
